export enum NotificationType {
  // Event lifecycle
  EVENT_SUBMITTED = 'EVENT_SUBMITTED',
  EVENT_SUBMITTED_OWNER = 'EVENT_SUBMITTED_OWNER',
  EVENT_APPROVED = 'EVENT_APPROVED',
  EVENT_REJECTED = 'EVENT_REJECTED',
  EVENT_LIVE = 'EVENT_LIVE',
  EVENT_CANCELLED = 'EVENT_CANCELLED',

  // Registration
  REGISTRATION_CONFIRMED = 'REGISTRATION_CONFIRMED',
  REGISTRATION_CANCELLED = 'REGISTRATION_CANCELLED',
  REGISTRATION_APPROVED = 'REGISTRATION_APPROVED',
  REGISTRATION_REJECTED = 'REGISTRATION_REJECTED',
  REGISTRATION_REMOVED = 'REGISTRATION_REMOVED',
  WAITLIST_JOINED = 'WAITLIST_JOINED',
  WAITLIST_PROMOTED = 'WAITLIST_PROMOTED',

  // Invitations / Organizers
  INVITATION_RECEIVED = 'INVITATION_RECEIVED',
  ORGANIZER_INVITE_ACCEPTED = 'ORGANIZER_INVITE_ACCEPTED',
  ORGANIZER_INVITE_REJECTED = 'ORGANIZER_INVITE_REJECTED',

  // General
  ANNOUNCEMENT = 'ANNOUNCEMENT',
}
